In [68]:
import pandas as pd
import numpy as np
import torch 
from sklearn.metrics import classification_report

In [2]:
img_pred = pd.read_csv('./race_prediction_image/userid_race_predrace.csv')

In [3]:
tweet_pred = pd.read_csv('./race_prediction_image/tweets_race_pred_prob.csv')

In [4]:
img_pred['0'].value_counts()

-0.204718    1
 0.231514    1
-3.421335    1
 0.838700    1
 1.421240    1
            ..
-0.021473    1
-2.295494    1
 0.867356    1
 1.929312    1
 0.435083    1
Name: 0, Length: 2385, dtype: int64

In [5]:
img_pred.columns

Index(['user_id', 'race', '0', '1', '2', '3'], dtype='object')

In [6]:
tweet_pred.head()

Unnamed: 0                                               text  label  \
0      257382  idk what you talking about this really good ad...    0.0   
1       33982                             otra vez con del haarp    0.0   
2      130380        lucky girl have guy who can make this happy    0.0   
3       49299  group there poll for cutest pop punk couple an...    0.0   
4       80981                                               gold    0.0   

     user_id  race_pred  pred_prob_0  pred_prob_1  pred_prob_2  pred_prob_3  
0   27542169          1     0.156823     0.425917     0.133472     0.243439  
1  109141099          3     0.163733     0.145553     0.080450     0.870215  
2  221521353          1     0.173984     0.534948     0.084354     0.187680  
3   16279572          0     0.468965     0.268325     0.142474     0.182471  
4  156734366          3     0.154191     0.253444     0.159758     0.397459

In [9]:
race_merged = pd.merge(img_pred, tweet_pred, on='user_id')

In [88]:
race_merged.dropna(inplace=True)
race_merged

user_id  race         0         1         2         3  Unnamed: 0  \
0      8.116180e+05   3.0 -0.204718 -1.788146  0.308982  1.711257       85010   
1      8.116180e+05   3.0 -0.204718 -1.788146  0.308982  1.711257      307778   
2      8.116180e+05   3.0 -0.204718 -1.788146  0.308982  1.711257      157082   
3      8.116180e+05   3.0 -0.204718 -1.788146  0.308982  1.711257      193118   
4      8.116180e+05   3.0 -0.204718 -1.788146  0.308982  1.711257      248810   
...             ...   ...       ...       ...       ...       ...         ...   
11960  4.809960e+09   4.0 -2.596924  3.136068 -1.222564  0.323277      218014   
11961  4.844349e+09   4.0 -0.459949 -2.541284  1.085653  1.628725      313020   
11973  4.878927e+09   4.0 -1.145033  1.878182 -1.201468  0.566636       67323   
11974  4.889566e+09   4.0  2.096782 -2.258169 -0.388432  1.017462       96808   
11975  4.892222e+09   4.0  3.942441 -4.115272  0.500873  0.184314      145949   

                                                    text  label  race_pred  \
0      sucks missed comic con again this year nxt yea...    2.0          0   
1                                        mins ago  they     2.0          2   
2         added music section admiring darthlaurain pict    2.0          0   
3                 saw santana barnes noble wantd tak shy    2.0          2   
4      started new blog sum reason felt like painting...    2.0          1   
...                                                  ...    ...        ...   
11960                         bold prediction there haha    0.0          2   
11961                      aquí esperando que vengan por    0.0          3   
11973      the rothschild dynasty laughing all right now    0.0          1   
11974  learn how mute everyone during your zoom lesso...    0.0          0   
11975                                               amen    0.0          1   

       pred_prob_0  pred_prob_1  pred_prob_2  pred_prob_3  
0         0.276591     0.261387     0.152498     0.237250  
1         0.259486     0.212014     0.290972     0.169673  
2         0.340545     0.322841     0.222665     0.054650  
3         0.039802     0.067998     0.903311     0.043624  
4         0.259072     0.305895     0.154612     0.187391  
...            ...          ...          ...          ...  
11960     0.239852     0.127929     0.375664     0.225400  
11961     0.100536     0.091231     0.076909     0.840464  
11973     0.235673     0.529555     0.075981     0.164567  
11974     0.302022     0.300096     0.248067     0.081283  
11975     0.150264     0.793629     0.036844     0.084671  

[8205 rows x 14 columns]

In [101]:
img_prob0 = race_merged['0'].to_numpy()
img_prob1 = race_merged['1'].to_numpy()
img_prob2 = race_merged['2'].to_numpy()
img_prob3 = race_merged['3'].to_numpy()

tweet_prob0 = race_merged['pred_prob_0'].to_numpy()
tweet_prob1 = race_merged['pred_prob_1'].to_numpy()
tweet_prob2 = race_merged['pred_prob_2'].to_numpy()
tweet_prob3 = race_merged['pred_prob_3'].to_numpy()

In [102]:
img_prob = np.vstack((img_prob0, img_prob1, img_prob2, img_prob3)).T
print(img_prob.shape)

tweet_prob = np.vstack((tweet_prob0, tweet_prob1, tweet_prob2, tweet_prob3)).T
tweet_prob.shape

(8205, 4)


(8205, 4)

In [103]:
from sklearn import preprocessing
norm_img_prob = preprocessing.normalize(img_prob)
print(norm_img_prob)

norm_tweet_prob = preprocessing.normalize(tweet_prob)
norm_tweet_prob

[[-0.08180041 -0.71450174  0.12346194  0.68377855]
 [-0.08180041 -0.71450174  0.12346194  0.68377855]
 [-0.08180041 -0.71450174  0.12346194  0.68377855]
 ...
 [-0.44559296  0.73090046 -0.46755497  0.22050803]
 [ 0.64154692 -0.69092607 -0.1188474   0.31131016]
 [ 0.68876709 -0.71896162  0.08750541  0.03220067]]


array([[0.58392467, 0.55182538, 0.32194654, 0.5008704 ],
       [0.54615105, 0.44623427, 0.61242134, 0.35711918],
       [0.65205018, 0.61815276, 0.42634285, 0.10463983],
       ...,
       [0.38805957, 0.87196827, 0.12511055, 0.27097685],
       [0.60474616, 0.6008911 , 0.49671204, 0.1627548 ],
       [0.18482893, 0.97618534, 0.0453188 , 0.10414724]])

#### Race Prediction based on probability returned by image

In [108]:
preds = np.argmax(img_prob, axis = 1)
print(preds)
print(classification_report(race_merged['label'], preds))

[3 3 3 ... 1 0 0]
              precision    recall  f1-score   support

         0.0       0.62      0.55      0.59      2087
         1.0       0.82      0.95      0.88      2085
         2.0       0.88      0.39      0.54      1960
         3.0       0.55      0.82      0.66      2073

    accuracy                           0.68      8205
   macro avg       0.72      0.68      0.67      8205
weighted avg       0.72      0.68      0.67      8205



#### Race Prediction based on probability returned by tweer

In [109]:
preds = np.argmax(tweet_prob, axis = 1)
print(preds)
print(classification_report(race_merged['label'], preds))

[0 2 0 ... 1 0 1]
              precision    recall  f1-score   support

         0.0       0.39      0.18      0.25      2087
         1.0       0.31      0.87      0.46      2085
         2.0       0.70      0.23      0.34      1960
         3.0       0.50      0.21      0.29      2073

    accuracy                           0.37      8205
   macro avg       0.47      0.37      0.34      8205
weighted avg       0.47      0.37      0.34      8205



#### Race Prediction based on probability returned by image and bert model

In [106]:
probs = tweet_prob + img_prob
preds = np.argmax(probs, axis = 1)
print(preds)
print(classification_report(race_merged['label'], preds))

[3 3 3 ... 1 0 0]
              precision    recall  f1-score   support

         0.0       0.64      0.56      0.60      2087
         1.0       0.77      0.96      0.86      2085
         2.0       0.91      0.43      0.58      1960
         3.0       0.59      0.82      0.69      2073

    accuracy                           0.70      8205
   macro avg       0.73      0.69      0.68      8205
weighted avg       0.73      0.70      0.68      8205



## age predition

In [25]:
img_age_pred = pd.read_csv('./age_prediction_image/age_precition_dataset2.csv', lineterminator='\n')

In [29]:
img_age_pred = img_age_pred.rename(columns={'id': 'screen_name'})
img_age_pred

screen_name  label        P0        P1
0             3d3lyn      0  0.000860  0.999140
1    TheRealKamerynB      0  0.522079  0.477921
2          tszymczak      1  0.814350  0.185650
3         LSwokowski      0  0.449531  0.550469
4          anerito97      1  0.013241  0.986759
..               ...    ...       ...       ...
682      cheesenip14      1  0.975255  0.024745
683       Y2ktagAdam      1  0.235382  0.764618
684      DysonReagan      1  0.022849  0.977151
685     flowers_anis      1  0.017637  0.982363
686    duenas_irving      0  0.987063  0.012936

[687 rows x 4 columns]

In [27]:
tweet_age_pred = pd.read_csv('./age_prediction_image/tweets_age_pred_prob.csv')
tweet_age_pred

Unnamed: 0                                               text  label  \
0          95238                    what the reason kindly fuck off      0   
1          14152                                               slur      0   
2          33880                                               yeah      0   
3          89400                      manifest great things tonight      0   
4          77151  really easy say all these words but you not ac...      0   
...          ...                                                ...    ...   
9995       92226                                  did say virtually      1   
9996       53017                     got first session tomorrow and      1   
9997       16545                                      sunday funday      1   
9998       87501  just college bro every fucking party went too ...      1   
9999       19299                                                but      1   

         screen_name  age_pred  pred_prob_0  pred_prob_1  
0      jay_littell99         0    -0.609488    -0.784449  
1       sapphiceevee         0    -0.652931    -0.735049  
2        erin_belle_         0    -0.588137    -0.810493  
3        Amandabookk         1    -0.721628    -0.665455  
4             serkif         1    -0.836983    -0.567422  
...              ...       ...          ...          ...  
9995     DocHoIIiday         0    -0.638387    -0.751081  
9996       Lil_OSO97         0    -0.635889    -0.753884  
9997  TheeHenryAdjah         1    -0.713750    -0.672960  
9998   StylezxGaming         0    -0.593784    -0.803484  
9999   nick_guarino3         0    -0.581281    -0.819122  

[10000 rows x 7 columns]

In [30]:
age_merged = pd.merge(img_age_pred, tweet_age_pred, on='screen_name')

In [31]:
age_merged

screen_name  label_x        P0        P1  Unnamed: 0  \
0            3d3lyn        0  0.000860  0.999140       77902   
1            3d3lyn        0  0.000860  0.999140       96222   
2            3d3lyn        0  0.000860  0.999140       17217   
3            3d3lyn        0  0.000860  0.999140       80192   
4            3d3lyn        0  0.000860  0.999140      108817   
...             ...      ...       ...       ...         ...   
6084  duenas_irving        0  0.987063  0.012936       84224   
6085  duenas_irving        0  0.987063  0.012936       73919   
6086  duenas_irving        0  0.987063  0.012936       39569   
6087  duenas_irving        0  0.987063  0.012936       17814   
6088  duenas_irving        0  0.987063  0.012936       43004   

                                                   text  label_y  age_pred  \
0                                             maybe not        0         0   
1                                                 babie        0         0   
2                                                  yuri        0         0   
3     yeah think should but think should ask delete ...        0         0   
4                                               goodbye        0         0   
...                                                 ...      ...       ...   
6084                               right next you chill        0         0   
6085           pero viene cumpleaños thats when all hit        0         1   
6086          should say louder for the people the back        0         0   
6087                havent been this sober weekend days        0         0   
6088                                     same cant wait        0         0   

      pred_prob_0  pred_prob_1  
0       -0.527265    -0.892128  
1       -0.554627    -0.853988  
2       -0.480969    -0.962816  
3       -0.684574    -0.701795  
4       -0.550664    -0.859359  
...           ...          ...  
6084    -0.591395    -0.806438  
6085    -0.794063    -0.601488  
6086    -0.656535    -0.731151  
6087    -0.589470    -0.808830  
6088    -0.584521    -0.815028  

[6089 rows x 10 columns]

In [110]:
img_prob0 = age_merged['P0'].to_numpy()
img_prob1 = age_merged['P1'].to_numpy()
tweet_prob0 = 1 + age_merged['pred_prob_0'].to_numpy()
tweet_prob1 = 1 + age_merged['pred_prob_1'].to_numpy()

In [111]:
img_prob = np.vstack((img_prob0, img_prob1)).T
tweet_prob = np.vstack((tweet_prob0, tweet_prob1)).T

In [112]:
norm_tweet_prob = preprocessing.normalize(tweet_prob)
norm_img_prob = preprocessing.normalize(img_prob)

#### Prediction based on probability returned by image

In [117]:
preds = np.argmax(img_prob, axis = 1)
print(classification_report(age_merged['label_y'], preds))

              precision    recall  f1-score   support

           0       0.55      0.28      0.37      3255
           1       0.47      0.73      0.57      2834

    accuracy                           0.49      6089
   macro avg       0.51      0.51      0.47      6089
weighted avg       0.51      0.49      0.47      6089



#### Prediction based on probability returned by tweets

In [118]:
preds = np.argmax(tweet_prob, axis = 1)
print(classification_report(age_merged['label_y'], preds))

              precision    recall  f1-score   support

           0       0.58      0.64      0.61      3255
           1       0.53      0.47      0.50      2834

    accuracy                           0.56      6089
   macro avg       0.56      0.56      0.56      6089
weighted avg       0.56      0.56      0.56      6089



#### Prediction based on probability returned by image and bert model

In [120]:
probs = (tweet_prob * 0.7) + (img_prob * 0.3)
preds = np.argmax(probs, axis = 1)
print(classification_report(age_merged['label_y'], preds))

              precision    recall  f1-score   support

           0       0.60      0.36      0.45      3255
           1       0.49      0.72      0.59      2834

    accuracy                           0.53      6089
   macro avg       0.54      0.54      0.52      6089
weighted avg       0.55      0.53      0.51      6089

